<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

class CreateLabeliconsTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('labelicons', function (Blueprint $table) {
            $table->string('id');
            $table->string('category')->nullable();
            $table->timestamps();
        });
        DB::table('labelicons')->insert(
            [
                    [ 'id' => 'fa-american-sign-language-interpreting', 'category' => 'Accebility'],
                    [ 'id' => 'fa-assistive-listening-systems', 'category' => 'Accebility'],
                    [ 'id' => 'fa-audio-description', 'category' => 'Accebility'],
                    [ 'id' => 'fa-blind', 'category' => 'Accebility'],
                    [ 'id' => 'fa-braille', 'category' => 'Accebility'],
                    [ 'id' => 'fa-closed-captioning', 'category' => 'Accebility'],
                    [ 'id' => 'fa-deaf', 'category' => 'Accebility'],
                    [ 'id' => 'fa-low-vision', 'category' => 'Accebility'],
                    [ 'id' => 'fa-phone-volume', 'category' => 'Accebility'],
                    [ 'id' => 'fa-question-circle', 'category' => 'Accebility'],
                    [ 'id' => 'fa-sign-language', 'category' => 'Accebility'],
                    [ 'id' => 'fa-tty', 'category' => 'Accebility'],
                    [ 'id' => 'fa-universal-access', 'category' => 'Accebility'],
                    [ 'id' => 'fa-wheelchair', 'category' => 'Accebility'],
                    [ 'id' => 'fa-bell', 'category' => 'Alert'],
                    [ 'id' => 'fa-bell-slash', 'category' => 'Alert'],
                    [ 'id' => 'fa-exclamation', 'category' => 'Alert'],
                    [ 'id' => 'fa-exclamation-circle', 'category' => 'Alert'],
                    [ 'id' => 'fa-exclamation-triangle', 'category' => 'Alert'],
                    [ 'id' => 'fa-radiation', 'category' => 'Alert'],
                    [ 'id' => 'fa-radiation-alt', 'category' => 'Alert'],
                    [ 'id' => 'fa-skull-crossbones', 'category' => 'Alert'],
                    [ 'id' => 'fa-cat', 'category' => 'Animals'],
                    [ 'id' => 'fa-crow', 'category' => 'Animals'],
                    [ 'id' => 'fa-dog', 'category' => 'Animals'],
                    [ 'id' => 'fa-dove', 'category' => 'Animals'],
                    [ 'id' => 'fa-dragon', 'category' => 'Animals'],
                    [ 'id' => 'fa-feather', 'category' => 'Animals'],
                    [ 'id' => 'fa-feather-alt', 'category' => 'Animals'],
                    [ 'id' => 'fa-fish', 'category' => 'Animals'],
                    [ 'id' => 'fa-frog', 'category' => 'Animals'],
                    [ 'id' => 'fa-hippo', 'category' => 'Animals'],
                    [ 'id' => 'fa-horse', 'category' => 'Animals'],
                    [ 'id' => 'fa-horse-head', 'category' => 'Animals'],
                    [ 'id' => 'fa-kiwi-bird', 'category' => 'Animals'],
                    [ 'id' => 'fa-otter', 'category' => 'Animals'],
                    [ 'id' => 'fa-paw', 'category' => 'Animals'],
                    [ 'id' => 'fa-spider', 'category' => 'Animals'],
                    [ 'id' => 'fa-angle-double-down', 'category' => 'Arrows'],
                    [ 'id' => 'fa-angle-double-left', 'category' => 'Arrows'],
                    [ 'id' => 'fa-angle-double-right', 'category' => 'Arrows'],
                    [ 'id' => 'fa-angle-double-up', 'category' => 'Arrows'],
                    [ 'id' => 'fa-angle-down', 'category' => 'Arrows'],
                    [ 'id' => 'fa-angle-left', 'category' => 'Arrows'],
                    [ 'id' => 'fa-angle-right', 'category' => 'Arrows'],
                    [ 'id' => 'fa-angle-up', 'category' => 'Arrows'],
                    [ 'id' => 'fa-arrow-alt-circle-down', 'category' => 'Arrows'],
                    [ 'id' => 'fa-arrow-alt-circle-left', 'category' => 'Arrows'],
                    [ 'id' => 'fa-arrow-alt-circle-right', 'category' => 'Arrows'],
                    [ 'id' => 'fa-arrow-alt-circle-up', 'category' => 'Arrows'],
                    [ 'id' => 'fa-arrow-circle-down', 'category' => 'Arrows'],
                    [ 'id' => 'fa-arrow-circle-left', 'category' => 'Arrows'],
                    [ 'id' => 'fa-arrow-circle-right', 'category' => 'Arrows'],
                    [ 'id' => 'fa-arrow-circle-up', 'category' => 'Arrows'],
                    [ 'id' => 'fa-arrow-down', 'category' => 'Arrows'],
                    [ 'id' => 'fa-arrow-left', 'category' => 'Arrows'],
                    [ 'id' => 'fa-arrow-right', 'category' => 'Arrows'],
                    [ 'id' => 'fa-arrow-up', 'category' => 'Arrows'],
                    [ 'id' => 'fa-arrows-alt', 'category' => 'Arrows'],
                    [ 'id' => 'fa-arrows-alt-h', 'category' => 'Arrows'],
                    [ 'id' => 'fa-arrows-alt-v', 'category' => 'Arrows'],
                    [ 'id' => 'fa-caret-down', 'category' => 'Arrows'],
                    [ 'id' => 'fa-caret-left', 'category' => 'Arrows'],
                    [ 'id' => 'fa-caret-right', 'category' => 'Arrows'],
                    [ 'id' => 'fa-caret-square-down', 'category' => 'Arrows'],
                    [ 'id' => 'fa-caret-square-left', 'category' => 'Arrows'],
                    [ 'id' => 'fa-caret-square-right', 'category' => 'Arrows'],
                    [ 'id' => 'fa-caret-square-up', 'category' => 'Arrows'],
                    [ 'id' => 'fa-caret-up', 'category' => 'Arrows'],
                    [ 'id' => 'fa-cart-arrow-down', 'category' => 'Arrows'],
                    [ 'id' => 'fa-chart-line', 'category' => 'Arrows'],
                    [ 'id' => 'fa-chevron-circle-down', 'category' => 'Arrows'],
                    [ 'id' => 'fa-chevron-circle-left', 'category' => 'Arrows'],
                    [ 'id' => 'fa-chevron-circle-right', 'category' => 'Arrows'],
                    [ 'id' => 'fa-chevron-circle-up', 'category' => 'Arrows'],
                    [ 'id' => 'fa-chevron-down', 'category' => 'Arrows'],
                    [ 'id' => 'fa-chevron-left', 'category' => 'Arrows'],
                    [ 'id' => 'fa-chevron-right', 'category' => 'Arrows'],
                    [ 'id' => 'fa-chevron-up', 'category' => 'Arrows'],
                    [ 'id' => 'fa-cloud-download-alt', 'category' => 'Arrows'],
                    [ 'id' => 'fa-cloud-upload-alt', 'category' => 'Arrows'],
                    [ 'id' => 'fa-compress-alt', 'category' => 'Arrows'],
                    [ 'id' => 'fa-compress-arrows-alt', 'category' => 'Arrows'],
                    [ 'id' => 'fa-download', 'category' => 'Arrows'],
                    [ 'id' => 'fa-exchange-alt', 'category' => 'Arrows'],
                    [ 'id' => 'fa-expand-alt', 'category' => 'Arrows'],
                    [ 'id' => 'fa-expand-arrows-alt', 'category' => 'Arrows'],
                    [ 'id' => 'fa-external-link-alt', 'category' => 'Arrows'],
                    [ 'id' => 'fa-external-link-square-alt', 'category' => 'Arrows'],
                    [ 'id' => 'fa-hand-point-down', 'category' => 'Arrows'],
                    [ 'id' => 'fa-hand-point-left', 'category' => 'Arrows'],
                    [ 'id' => 'fa-hand-point-right', 'category' => 'Arrows'],
                    [ 'id' => 'fa-hand-point-up', 'category' => 'Arrows'],
                    [ 'id' => 'fa-hand-pointer', 'category' => 'Arrows'],
                    [ 'id' => 'fa-history', 'category' => 'Arrows'],
                    [ 'id' => 'fa-level-down-alt', 'category' => 'Arrows'],
                    [ 'id' => 'fa-level-up-alt', 'category' => 'Arrows'],
                    [ 'id' => 'fa-location-arrow', 'category' => 'Arrows'],
                    [ 'id' => 'fa-long-arrow-alt-down', 'category' => 'Arrows'],
                    [ 'id' => 'fa-long-arrow-alt-left', 'category' => 'Arrows'],
                    [ 'id' => 'fa-long-arrow-alt-right', 'category' => 'Arrows'],
                    [ 'id' => 'fa-long-arrow-alt-up', 'category' => 'Arrows'],
                    [ 'id' => 'fa-mouse-pointer', 'category' => 'Arrows'],
                    [ 'id' => 'fa-play', 'category' => 'Arrows'],
                    [ 'id' => 'fa-random', 'category' => 'Arrows'],
                    [ 'id' => 'fa-recycle', 'category' => 'Arrows'],
                    [ 'id' => 'fa-redo', 'category' => 'Arrows'],
                    [ 'id' => 'fa-redo-alt', 'category' => 'Arrows'],
                    [ 'id' => 'fa-reply', 'category' => 'Arrows'],
                    [ 'id' => 'fa-reply-all', 'category' => 'Arrows'],
                    [ 'id' => 'fa-retweet', 'category' => 'Arrows'],
                    [ 'id' => 'fa-share', 'category' => 'Arrows'],
                    [ 'id' => 'fa-share-square', 'category' => 'Arrows'],
                    [ 'id' => 'fa-sign-in-alt', 'category' => 'Arrows'],
                    [ 'id' => 'fa-sign-out-alt', 'category' => 'Arrows'],
                    [ 'id' => 'fa-sort', 'category' => 'Arrows'],
                    [ 'id' => 'fa-sort-alpha-down', 'category' => 'Arrows'],
                    [ 'id' => 'fa-sort-alpha-down-alt', 'category' => 'Arrows'],
                    [ 'id' => 'fa-sort-alpha-up', 'category' => 'Arrows'],
                    [ 'id' => 'fa-sort-alpha-up-alt', 'category' => 'Arrows'],
                    [ 'id' => 'fa-sort-amount-down', 'category' => 'Arrows'],
                    [ 'id' => 'fa-sort-amount-down-alt', 'category' => 'Arrows'],
                    [ 'id' => 'fa-sort-amount-up', 'category' => 'Arrows'],
                    [ 'id' => 'fa-sort-amount-up-alt', 'category' => 'Arrows'],
                    [ 'id' => 'fa-sort-down', 'category' => 'Arrows'],
                    [ 'id' => 'fa-sort-numeric-down', 'category' => 'Arrows'],
                    [ 'id' => 'fa-sort-numeric-down-alt', 'category' => 'Arrows'],
                    [ 'id' => 'fa-sort-numeric-up', 'category' => 'Arrows'],
                    [ 'id' => 'fa-sort-numeric-up-alt', 'category' => 'Arrows'],
                    [ 'id' => 'fa-sort-up', 'category' => 'Arrows'],
                    [ 'id' => 'fa-sync', 'category' => 'Arrows'],
                    [ 'id' => 'fa-sync-alt', 'category' => 'Arrows'],
                    [ 'id' => 'fa-text-height', 'category' => 'Arrows'],
                    [ 'id' => 'fa-text-width', 'category' => 'Arrows'],
                    [ 'id' => 'fa-undo', 'category' => 'Arrows'],
                    [ 'id' => 'fa-undo-alt', 'category' => 'Arrows'],
                    [ 'id' => 'fa-upload', 'category' => 'Arrows'],
                    [ 'id' => 'fa-audio-description', 'category' => 'Audio & Video'],
                    [ 'id' => 'fa-backward', 'category' => 'Audio & Video'],
                    [ 'id' => 'fa-broadcast-tower', 'category' => 'Audio & Video'],
                    [ 'id' => 'fa-circle', 'category' => 'Audio & Video'],
                    [ 'id' => 'fa-closed-captioning', 'category' => 'Audio & Video'],
                    [ 'id' => 'fa-compress', 'category' => 'Audio & Video'],
                    [ 'id' => 'fa-compress-alt', 'category' => 'Audio & Video'],
                    [ 'id' => 'fa-compress-arrows-alt', 'category' => 'Audio & Video'],
                    [ 'id' => 'fa-eject', 'category' => 'Audio & Video'],
                    [ 'id' => 'fa-expand', 'category' => 'Audio & Video'],
                    [ 'id' => 'fa-expand-alt', 'category' => 'Audio & Video'],
                    [ 'id' => 'fa-expand-arrows-alt', 'category' => 'Audio & Video'],
                    [ 'id' => 'fa-fast-backward', 'category' => 'Audio & Video'],
                    [ 'id' => 'fa-fast-forward', 'category' => 'Audio & Video'],
                    [ 'id' => 'fa-file-audio', 'category' => 'Audio & Video'],
                    [ 'id' => 'fa-file-video', 'category' => 'Audio & Video'],
                    [ 'id' => 'fa-film', 'category' => 'Audio & Video'],
                    [ 'id' => 'fa-forward', 'category' => 'Audio & Video'],
                    [ 'id' => 'fa-headphones', 'category' => 'Audio & Video'],
                    [ 'id' => 'fa-microphone', 'category' => 'Audio & Video'],
                    [ 'id' => 'fa-microphone-alt', 'category' => 'Audio & Video'],
                    [ 'id' => 'fa-microphone-alt-slash', 'category' => 'Audio & Video'],
                    [ 'id' => 'fa-microphone-slash', 'category' => 'Audio & Video'],
                    [ 'id' => 'fa-music', 'category' => 'Audio & Video'],
                    [ 'id' => 'fa-pause', 'category' => 'Audio & Video'],
                    [ 'id' => 'fa-pause-circle', 'category' => 'Audio & Video'],
                    [ 'id' => 'fa-phone-volume', 'category' => 'Audio & Video'],
                    [ 'id' => 'fa-photo-video', 'category' => 'Audio & Video'],
                    [ 'id' => 'fa-play', 'category' => 'Audio & Video'],
                    [ 'id' => 'fa-play-circle', 'category' => 'Audio & Video'],
                    [ 'id' => 'fa-podcast', 'category' => 'Audio & Video'],
                    [ 'id' => 'fa-random', 'category' => 'Audio & Video'],
                    [ 'id' => 'fa-redo', 'category' => 'Audio & Video'],
                    [ 'id' => 'fa-redo-alt', 'category' => 'Audio & Video'],
                    [ 'id' => 'fa-rss', 'category' => 'Audio & Video'],
                    [ 'id' => 'fa-rss-square', 'category' => 'Audio & Video'],
                    [ 'id' => 'fa-step-backward', 'category' => 'Audio & Video'],
                    [ 'id' => 'fa-step-forward', 'category' => 'Audio & Video'],
                    [ 'id' => 'fa-stop', 'category' => 'Audio & Video'],
                    [ 'id' => 'fa-stop-circle', 'category' => 'Audio & Video'],
                    [ 'id' => 'fa-sync', 'category' => 'Audio & Video'],
                    [ 'id' => 'fa-sync-alt', 'category' => 'Audio & Video'],
                    [ 'id' => 'fa-tv', 'category' => 'Audio & Video'],
                    [ 'id' => 'fa-undo', 'category' => 'Audio & Video'],
                    [ 'id' => 'fa-undo-alt', 'category' => 'Audio & Video'],
                    [ 'id' => 'fa-video', 'category' => 'Audio & Video'],
                    [ 'id' => 'fa-volume-down', 'category' => 'Audio & Video'],
                    [ 'id' => 'fa-volume-mute', 'category' => 'Audio & Video'],
                    [ 'id' => 'fa-volume-off', 'category' => 'Audio & Video'],
                    [ 'id' => 'fa-volume-up', 'category' => 'Audio & Video'],
                    [ 'id' => 'fa-air-freshener', 'category' => 'Automotive'],
                    [ 'id' => 'fa-ambulance', 'category' => 'Automotive'],
                    [ 'id' => 'fa-bus', 'category' => 'Automotive'],
                    [ 'id' => 'fa-bus-alt', 'category' => 'Automotive'],
                    [ 'id' => 'fa-car', 'category' => 'Automotive'],
                    [ 'id' => 'fa-car-alt', 'category' => 'Automotive'],
                    [ 'id' => 'fa-car-battery', 'category' => 'Automotive'],
                    [ 'id' => 'fa-car-crash', 'category' => 'Automotive'],
                    [ 'id' => 'fa-car-side', 'category' => 'Automotive'],
                    [ 'id' => 'fa-caravan', 'category' => 'Automotive'],
                    [ 'id' => 'fa-charging-station', 'category' => 'Automotive'],
                    [ 'id' => 'fa-gas-pump', 'category' => 'Automotive'],
                    [ 'id' => 'fa-motorcycle', 'category' => 'Automotive'],
                    [ 'id' => 'fa-oil-can', 'category' => 'Automotive'],
                    [ 'id' => 'fa-shuttle-van', 'category' => 'Automotive'],
                    [ 'id' => 'fa-tachometer-alt', 'category' => 'Automotive'],
                    [ 'id' => 'fa-taxi', 'category' => 'Automotive'],
                    [ 'id' => 'fa-trailer', 'category' => 'Automotive'],
                    [ 'id' => 'fa-truck', 'category' => 'Automotive'],
                    [ 'id' => 'fa-truck-monster', 'category' => 'Automotive'],
                    [ 'id' => 'fa-truck-pickup', 'category' => 'Automotive'],
                    [ 'id' => 'fa-apple-alt', 'category' => 'Autumn'],
                    [ 'id' => 'fa-campground', 'category' => 'Autumn'],
                    [ 'id' => 'fa-cloud-sun', 'category' => 'Autumn'],
                    [ 'id' => 'fa-drumstick-bite', 'category' => 'Autumn'],
                    [ 'id' => 'fa-football-ball', 'category' => 'Autumn'],
                    [ 'id' => 'fa-hiking', 'category' => 'Autumn'],
                    [ 'id' => 'fa-mountain', 'category' => 'Autumn'],
                    [ 'id' => 'fa-tractor', 'category' => 'Autumn'],
                    [ 'id' => 'fa-tree', 'category' => 'Autumn'],
                    [ 'id' => 'fa-wind', 'category' => 'Autumn'],
                    [ 'id' => 'fa-wine-bottle', 'category' => 'Autumn'],
                    [ 'id' => 'fa-beer', 'category' => 'Beverage'],
                    [ 'id' => 'fa-blender', 'category' => 'Beverage'],
                    [ 'id' => 'fa-cocktail', 'category' => 'Beverage'],
                    [ 'id' => 'fa-coffee', 'category' => 'Beverage'],
                    [ 'id' => 'fa-flask', 'category' => 'Beverage'],
                    [ 'id' => 'fa-glass-cheers', 'category' => 'Beverage'],
                    [ 'id' => 'fa-glass-martini', 'category' => 'Beverage'],
                    [ 'id' => 'fa-glass-martini-alt', 'category' => 'Beverage'],
                    [ 'id' => 'fa-glass-whiskey', 'category' => 'Beverage'],
                    [ 'id' => 'fa-mug-hot', 'category' => 'Beverage'],
                    [ 'id' => 'fa-wine-bottle', 'category' => 'Beverage'],
                    [ 'id' => 'fa-wine-glass', 'category' => 'Beverage'],
                    [ 'id' => 'fa-wine-glass-alt', 'category' => 'Beverage'],
                    [ 'id' => 'fa-archway', 'category' => 'Buildings'],
                    [ 'id' => 'fa-building', 'category' => 'Buildings'],
                    [ 'id' => 'fa-campground', 'category' => 'Buildings'],
                    [ 'id' => 'fa-church', 'category' => 'Buildings'],
                    [ 'id' => 'fa-city', 'category' => 'Buildings'],
                    [ 'id' => 'fa-clinic-medical', 'category' => 'Buildings'],
                    [ 'id' => 'fa-dungeon', 'category' => 'Buildings'],
                    [ 'id' => 'fa-gopuram', 'category' => 'Buildings'],
                    [ 'id' => 'fa-home', 'category' => 'Buildings'],
                    [ 'id' => 'fa-hospital', 'category' => 'Buildings'],
                    [ 'id' => 'fa-hospital-alt', 'category' => 'Buildings'],
                    [ 'id' => 'fa-hospital-user', 'category' => 'Buildings'],
                    [ 'id' => 'fa-hotel', 'category' => 'Buildings'],
                    [ 'id' => 'fa-house-damage', 'category' => 'Buildings'],
                    [ 'id' => 'fa-igloo', 'category' => 'Buildings'],
                    [ 'id' => 'fa-industry', 'category' => 'Buildings'],
                    [ 'id' => 'fa-kaaba', 'category' => 'Buildings'],
                    [ 'id' => 'fa-landmark', 'category' => 'Buildings'],
                    [ 'id' => 'fa-monument', 'category' => 'Buildings'],
                    [ 'id' => 'fa-mosque', 'category' => 'Buildings'],
                    [ 'id' => 'fa-place-of-worship', 'category' => 'Buildings'],
                    [ 'id' => 'fa-school', 'category' => 'Buildings'],
                    [ 'id' => 'fa-store', 'category' => 'Buildings'],
                    [ 'id' => 'fa-store-alt', 'category' => 'Buildings'],
                    [ 'id' => 'fa-synagogue', 'category' => 'Buildings'],
                    [ 'id' => 'fa-torii-gate', 'category' => 'Buildings'],
                    [ 'id' => 'fa-university', 'category' => 'Buildings'],
                    [ 'id' => 'fa-vihara', 'category' => 'Buildings'],
                    [ 'id' => 'fa-warehouse', 'category' => 'Buildings'],
                    [ 'id' => 'fa-address-book', 'category' => 'Business'],
                    [ 'id' => 'fa-address-card', 'category' => 'Business'],
                    [ 'id' => 'fa-archive', 'category' => 'Business'],
                    [ 'id' => 'fa-balance-scale', 'category' => 'Business'],
                    [ 'id' => 'fa-balance-scale-left', 'category' => 'Business'],
                    [ 'id' => 'fa-balance-scale-right', 'category' => 'Business'],
                    [ 'id' => 'fa-birthday-cake', 'category' => 'Business'],
                    [ 'id' => 'fa-book', 'category' => 'Business'],
                    [ 'id' => 'fa-briefcase', 'category' => 'Business'],
                    [ 'id' => 'fa-building', 'category' => 'Business'],
                    [ 'id' => 'fa-bullhorn', 'category' => 'Business'],
                    [ 'id' => 'fa-bullseye', 'category' => 'Business'],
                    [ 'id' => 'fa-business-time', 'category' => 'Business'],
                    [ 'id' => 'fa-calculator', 'category' => 'Business'],
                    [ 'id' => 'fa-calendar', 'category' => 'Business'],
                    [ 'id' => 'fa-calendar-alt', 'category' => 'Business'],
                    [ 'id' => 'fa-certificate', 'category' => 'Business'],
                    [ 'id' => 'fa-chart-area', 'category' => 'Business'],
                    [ 'id' => 'fa-chart-bar', 'category' => 'Business'],
                    [ 'id' => 'fa-chart-line', 'category' => 'Business'],
                    [ 'id' => 'fa-chart-pie', 'category' => 'Business'],
                    [ 'id' => 'fa-city', 'category' => 'Business'],
                    [ 'id' => 'fa-clipboard', 'category' => 'Business'],
                    [ 'id' => 'fa-coffee', 'category' => 'Business'],
                    [ 'id' => 'fa-columns', 'category' => 'Business'],
                    [ 'id' => 'fa-compass', 'category' => 'Business'],
                    [ 'id' => 'fa-copy', 'category' => 'Business'],
                    [ 'id' => 'fa-copyright', 'category' => 'Business'],
                    [ 'id' => 'fa-cut', 'category' => 'Business'],
                    [ 'id' => 'fa-edit', 'category' => 'Business'],
                    [ 'id' => 'fa-envelope', 'category' => 'Business'],
                    [ 'id' => 'fa-envelope-open', 'category' => 'Business'],
                    [ 'id' => 'fa-envelope-square', 'category' => 'Business'],
                    [ 'id' => 'fa-eraser', 'category' => 'Business'],
                    [ 'id' => 'fa-fax', 'category' => 'Business'],
                    [ 'id' => 'fa-file', 'category' => 'Business'],
                    [ 'id' => 'fa-file-alt', 'category' => 'Business'],
                    [ 'id' => 'fa-folder', 'category' => 'Business'],
                    [ 'id' => 'fa-folder-minus', 'category' => 'Business'],
                    [ 'id' => 'fa-folder-open', 'category' => 'Business'],
                    [ 'id' => 'fa-folder-plus', 'category' => 'Business'],
                    [ 'id' => 'fa-glasses', 'category' => 'Business'],
                    [ 'id' => 'fa-globe', 'category' => 'Business'],
                    [ 'id' => 'fa-highlighter', 'category' => 'Business'],
                    [ 'id' => 'fa-industry', 'category' => 'Business'],
                    [ 'id' => 'fa-landmark', 'category' => 'Business'],
                    [ 'id' => 'fa-laptop-house', 'category' => 'Business'],
                    [ 'id' => 'fa-marker', 'category' => 'Business'],
                    [ 'id' => 'fa-paperclip', 'category' => 'Business'],
                    [ 'id' => 'fa-paste', 'category' => 'Business'],
                    [ 'id' => 'fa-pen', 'category' => 'Business'],
                    [ 'id' => 'fa-pen-alt', 'category' => 'Business'],
                    [ 'id' => 'fa-pen-fancy', 'category' => 'Business'],
                    [ 'id' => 'fa-pen-nib', 'category' => 'Business'],
                    [ 'id' => 'fa-pen-square', 'category' => 'Business'],
                    [ 'id' => 'fa-pencil-alt', 'category' => 'Business'],
                    [ 'id' => 'fa-percent', 'category' => 'Business'],
                    [ 'id' => 'fa-phone', 'category' => 'Business'],
                    [ 'id' => 'fa-phone-alt', 'category' => 'Business'],
                    [ 'id' => 'fa-phone-slash', 'category' => 'Business'],
                    [ 'id' => 'fa-phone-square', 'category' => 'Business'],
                    [ 'id' => 'fa-phone-square-alt', 'category' => 'Business'],
                    [ 'id' => 'fa-phone-volume', 'category' => 'Business'],
                    [ 'id' => 'fa-print', 'category' => 'Business'],
                    [ 'id' => 'fa-project-diagram', 'category' => 'Business'],
                    [ 'id' => 'fa-registered', 'category' => 'Business'],
                    [ 'id' => 'fa-save', 'category' => 'Business'],
                    [ 'id' => 'fa-sitemap', 'category' => 'Business'],
                    [ 'id' => 'fa-socks', 'category' => 'Business'],
                    [ 'id' => 'fa-sticky-note', 'category' => 'Business'],
                    [ 'id' => 'fa-stream', 'category' => 'Business'],
                    [ 'id' => 'fa-table', 'category' => 'Business'],
                    [ 'id' => 'fa-tag', 'category' => 'Business'],
                    [ 'id' => 'fa-tags', 'category' => 'Business'],
                    [ 'id' => 'fa-tasks', 'category' => 'Business'],
                    [ 'id' => 'fa-thumbtack', 'category' => 'Business'],
                    [ 'id' => 'fa-trademark', 'category' => 'Business'],
                    [ 'id' => 'fa-wallet', 'category' => 'Business'],

            ]
        );
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('labelicons');
    }
}
